### ISSUE TITLE
OSError: Error connecting to SOCKS5 proxy 127.0.0.1:9051: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by bklnf** [asmiller1989/tor_crawler#2]
when running simple lines got error.
torrc.sample configured properly
`
from TorCrawler import TorCrawler

import os
import socks
import socket

crawler = TorCrawler(ctrl_pass='121488') 
`

**Comment by fierzdev** [comment]
Make sure that you adjusted the torrc file and that the control Port is enabled. That should fix it.
